baseURL = 'https://blog.bigbee.dev/'
title = 'Big Bee'
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

enableRobotsTXT = true
enableEmoji     = true

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Soe Moe Tun Lwin"

[taxonomies]
  category = "blog"
  tag      = "tags"

[params]
  homeSubtitle = "Embrace Simplicity"

  [params.logo]
    logoMark     = ">"
    logoText     = "$ cd /home/"
    logoHomeLink = "/"
    logoCursorDisabled = true
  
  # Social icons
  [[params.social]]
    name = "email"
    url  = "mailto:hello@bigbee.dev"

  [[params.social]]
    name = "github"
    url  = "https://github.com/bigbee-dev"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "https://www.bigbee.dev"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
